---
# Usage: ansible-playbook playbooks/ccco_clean_osc.yaml
# Idempotent removal of the OpenShift Sandboxed Containers (OSC) Operator.

- name: Generate inventory hosts file from all.yaml
  hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - "{{ playbook_dir }}/../inventories/default/group_vars/all.yaml"
  tasks:
    - name: Set inventory
      ansible.builtin.import_role:
        name: ccco_setinventory

- name: Remove OpenShift Sandboxed Containers (OSC) Operator
  hosts: bastion
  gather_facts: false
  vars_files:
    - "{{ inventory_dir }}/group_vars/all.yaml"
  tasks:
    - name: Remove OSC Operator
      ansible.builtin.import_role:
        name: ccco_remove_osc
