---
# Usage: ansible-playbook playbooks/ccco_clean_nfd.yaml
# Idempotent removal of the Node Feature Discovery (NFD) Operator
# and all feature.node.kubernetes.io/* node labels.

- name: Generate inventory hosts file from all.yaml
  hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - "{{ playbook_dir }}/../inventories/default/group_vars/all.yaml"
  tasks:
    - name: Set inventory
      ansible.builtin.import_role:
        name: ccco_setinventory

- name: Remove Node Feature Discovery (NFD) Operator
  hosts: bastion
  gather_facts: false
  vars_files:
    - "{{ inventory_dir }}/group_vars/all.yaml"
  tasks:
    - name: Remove NFD Operator
      ansible.builtin.import_role:
        name: ccco_remove_nfd
